'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace HOSTReportService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="HOSTReportService.IReportWCF", CallbackContract:=GetType(HOSTReportService.IReportWCFCallback), SessionMode:=System.ServiceModel.SessionMode.Required)>  _
    Public Interface IReportWCF
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReportWCF/Connect", ReplyAction:="http://tempuri.org/IReportWCF/ConnectResponse")>  _
        Function Connect(ByVal pv_oClient As Sats.CommonLibrary.Client) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IReportWCF/Connect", ReplyAction:="http://tempuri.org/IReportWCF/ConnectResponse")>  _
        Function BeginConnect(ByVal pv_oClient As Sats.CommonLibrary.Client, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndConnect(ByVal result As System.IAsyncResult) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReportWCF/SendRpt", ReplyAction:="http://tempuri.org/IReportWCF/SendRptResponse")>  _
        Function SendRpt(ByRef pv_strMessage As String, ByRef pv_arrByte() As Byte) As Long
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IReportWCF/SendRpt", ReplyAction:="http://tempuri.org/IReportWCF/SendRptResponse")>  _
        Function BeginSendRpt(ByRef pv_strMessage As String, ByRef pv_arrByte() As Byte, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndSendRpt(ByRef pv_strMessage As String, ByRef pv_arrByte() As Byte, ByVal result As System.IAsyncResult) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReportWCF/SendExpRpt", ReplyAction:="http://tempuri.org/IReportWCF/SendExpRptResponse")>  _
        Function SendExpRpt(ByVal pv_strMessage As String) As Long
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IReportWCF/SendExpRpt", ReplyAction:="http://tempuri.org/IReportWCF/SendExpRptResponse")>  _
        Function BeginSendExpRpt(ByVal pv_strMessage As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndSendExpRpt(ByVal result As System.IAsyncResult) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReportWCF/FetchRpt", ReplyAction:="http://tempuri.org/IReportWCF/FetchRptResponse")>  _
        Function FetchRpt(ByVal pv_strRptDataKey As String, ByVal pv_intFrom As Integer, ByVal pv_intTo As Integer, ByRef pv_arrByte() As Byte) As Long
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IReportWCF/FetchRpt", ReplyAction:="http://tempuri.org/IReportWCF/FetchRptResponse")>  _
        Function BeginFetchRpt(ByVal pv_strRptDataKey As String, ByVal pv_intFrom As Integer, ByVal pv_intTo As Integer, ByRef pv_arrByte() As Byte, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndFetchRpt(ByRef pv_arrByte() As Byte, ByVal result As System.IAsyncResult) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReportWCF/SendRptCA", ReplyAction:="http://tempuri.org/IReportWCF/SendRptCAResponse")>  _
        Function SendRptCA(ByRef pv_strMessage As String, ByRef pv_arrByte() As Byte, ByRef v_strVSDSignature As String, ByRef v_strCAKey As String, ByRef pv_strDataHash As String) As Long
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IReportWCF/SendRptCA", ReplyAction:="http://tempuri.org/IReportWCF/SendRptCAResponse")>  _
        Function BeginSendRptCA(ByRef pv_strMessage As String, ByRef pv_arrByte() As Byte, ByRef v_strVSDSignature As String, ByRef v_strCAKey As String, ByRef pv_strDataHash As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndSendRptCA(ByRef pv_strMessage As String, ByRef pv_arrByte() As Byte, ByRef v_strVSDSignature As String, ByRef v_strCAKey As String, ByRef pv_strDataHash As String, ByVal result As System.IAsyncResult) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReportWCF/SaveFileRptCA", ReplyAction:="http://tempuri.org/IReportWCF/SaveFileRptCAResponse")>  _
        Function SaveFileRptCA(ByVal pv_arrByte() As Byte, ByVal v_strVSDSignature As String, ByVal v_strClientVSDSignature As String, ByVal v_strTLname As String, ByVal v_strRptId As String, ByRef v_strLocalDir As String, ByRef v_strFileName As String, ByVal v_strStatus As String) As Long
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IReportWCF/SaveFileRptCA", ReplyAction:="http://tempuri.org/IReportWCF/SaveFileRptCAResponse")>  _
        Function BeginSaveFileRptCA(ByVal pv_arrByte() As Byte, ByVal v_strVSDSignature As String, ByVal v_strClientVSDSignature As String, ByVal v_strTLname As String, ByVal v_strRptId As String, ByRef v_strLocalDir As String, ByRef v_strFileName As String, ByVal v_strStatus As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndSaveFileRptCA(ByRef v_strLocalDir As String, ByRef v_strFileName As String, ByVal result As System.IAsyncResult) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReportWCF/Disconnect", ReplyAction:="http://tempuri.org/IReportWCF/DisconnectResponse")>  _
        Sub Disconnect(ByVal pv_oClient As Sats.CommonLibrary.Client)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IReportWCF/Disconnect", ReplyAction:="http://tempuri.org/IReportWCF/DisconnectResponse")>  _
        Function BeginDisconnect(ByVal pv_oClient As Sats.CommonLibrary.Client, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndDisconnect(ByVal result As System.IAsyncResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IReportWCFCallback
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IReportWCF/Receive")>  _
        Sub Receive(ByVal pv_oMessage As String)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, AsyncPattern:=true, Action:="http://tempuri.org/IReportWCF/Receive")>  _
        Function BeginReceive(ByVal pv_oMessage As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndReceive(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IReportWCF/ReceiveAction")>  _
        Sub ReceiveAction(ByVal pv_oDataSet As System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, AsyncPattern:=true, Action:="http://tempuri.org/IReportWCF/ReceiveAction")>  _
        Function BeginReceiveAction(ByVal pv_oDataSet As System.Data.DataSet, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndReceiveAction(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IReportWCF/UserJoin")>  _
        Sub UserJoin(ByVal pv_oClient As Sats.CommonLibrary.Client)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, AsyncPattern:=true, Action:="http://tempuri.org/IReportWCF/UserJoin")>  _
        Function BeginUserJoin(ByVal pv_oClient As Sats.CommonLibrary.Client, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndUserJoin(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IReportWCF/UserLeave")>  _
        Sub UserLeave(ByVal pv_oClient As Sats.CommonLibrary.Client)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, AsyncPattern:=true, Action:="http://tempuri.org/IReportWCF/UserLeave")>  _
        Function BeginUserLeave(ByVal pv_oClient As Sats.CommonLibrary.Client, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndUserLeave(ByVal result As System.IAsyncResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IReportWCFChannel
        Inherits HOSTReportService.IReportWCF, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ConnectCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class SendRptCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property pv_strMessage() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        Public ReadOnly Property pv_arrByte() As Byte()
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Byte())
            End Get
        End Property
        
        Public ReadOnly Property Result() As Long
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(2),Long)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class SendExpRptCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Long
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class FetchRptCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property pv_arrByte() As Byte()
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
        
        Public ReadOnly Property Result() As Long
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Long)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class SendRptCACompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property pv_strMessage() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        Public ReadOnly Property pv_arrByte() As Byte()
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Byte())
            End Get
        End Property
        
        Public ReadOnly Property v_strVSDSignature() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
        
        Public ReadOnly Property v_strCAKey() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(3),String)
            End Get
        End Property
        
        Public ReadOnly Property pv_strDataHash() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(4),String)
            End Get
        End Property
        
        Public ReadOnly Property Result() As Long
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(5),Long)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class SaveFileRptCACompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property v_strLocalDir() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        Public ReadOnly Property v_strFileName() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        Public ReadOnly Property Result() As Long
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(2),Long)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ReportWCFClient
        Inherits System.ServiceModel.DuplexClientBase(Of HOSTReportService.IReportWCF)
        Implements HOSTReportService.IReportWCF
        
        Private onBeginConnectDelegate As BeginOperationDelegate
        
        Private onEndConnectDelegate As EndOperationDelegate
        
        Private onConnectCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginSendRptDelegate As BeginOperationDelegate
        
        Private onEndSendRptDelegate As EndOperationDelegate
        
        Private onSendRptCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginSendExpRptDelegate As BeginOperationDelegate
        
        Private onEndSendExpRptDelegate As EndOperationDelegate
        
        Private onSendExpRptCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginFetchRptDelegate As BeginOperationDelegate
        
        Private onEndFetchRptDelegate As EndOperationDelegate
        
        Private onFetchRptCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginSendRptCADelegate As BeginOperationDelegate
        
        Private onEndSendRptCADelegate As EndOperationDelegate
        
        Private onSendRptCACompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginSaveFileRptCADelegate As BeginOperationDelegate
        
        Private onEndSaveFileRptCADelegate As EndOperationDelegate
        
        Private onSaveFileRptCACompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginDisconnectDelegate As BeginOperationDelegate
        
        Private onEndDisconnectDelegate As EndOperationDelegate
        
        Private onDisconnectCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext)
            MyBase.New(callbackInstance)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String)
            MyBase.New(callbackInstance, endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, binding, remoteAddress)
        End Sub
        
        Public Event ConnectCompleted As System.EventHandler(Of ConnectCompletedEventArgs)
        
        Public Event SendRptCompleted As System.EventHandler(Of SendRptCompletedEventArgs)
        
        Public Event SendExpRptCompleted As System.EventHandler(Of SendExpRptCompletedEventArgs)
        
        Public Event FetchRptCompleted As System.EventHandler(Of FetchRptCompletedEventArgs)
        
        Public Event SendRptCACompleted As System.EventHandler(Of SendRptCACompletedEventArgs)
        
        Public Event SaveFileRptCACompleted As System.EventHandler(Of SaveFileRptCACompletedEventArgs)
        
        Public Event DisconnectCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Function Connect(ByVal pv_oClient As Sats.CommonLibrary.Client) As Boolean Implements HOSTReportService.IReportWCF.Connect
            Return MyBase.Channel.Connect(pv_oClient)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginConnect(ByVal pv_oClient As Sats.CommonLibrary.Client, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements HOSTReportService.IReportWCF.BeginConnect
            Return MyBase.Channel.BeginConnect(pv_oClient, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndConnect(ByVal result As System.IAsyncResult) As Boolean Implements HOSTReportService.IReportWCF.EndConnect
            Return MyBase.Channel.EndConnect(result)
        End Function
        
        Private Function OnBeginConnect(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pv_oClient As Sats.CommonLibrary.Client = CType(inValues(0),Sats.CommonLibrary.Client)
            Return Me.BeginConnect(pv_oClient, callback, asyncState)
        End Function
        
        Private Function OnEndConnect(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Boolean = Me.EndConnect(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnConnectCompleted(ByVal state As Object)
            If (Not (Me.ConnectCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ConnectCompleted(Me, New ConnectCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ConnectAsync(ByVal pv_oClient As Sats.CommonLibrary.Client)
            Me.ConnectAsync(pv_oClient, Nothing)
        End Sub
        
        Public Overloads Sub ConnectAsync(ByVal pv_oClient As Sats.CommonLibrary.Client, ByVal userState As Object)
            If (Me.onBeginConnectDelegate Is Nothing) Then
                Me.onBeginConnectDelegate = AddressOf Me.OnBeginConnect
            End If
            If (Me.onEndConnectDelegate Is Nothing) Then
                Me.onEndConnectDelegate = AddressOf Me.OnEndConnect
            End If
            If (Me.onConnectCompletedDelegate Is Nothing) Then
                Me.onConnectCompletedDelegate = AddressOf Me.OnConnectCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginConnectDelegate, New Object() {pv_oClient}, Me.onEndConnectDelegate, Me.onConnectCompletedDelegate, userState)
        End Sub
        
        Public Function SendRpt(ByRef pv_strMessage As String, ByRef pv_arrByte() As Byte) As Long Implements HOSTReportService.IReportWCF.SendRpt
            Return MyBase.Channel.SendRpt(pv_strMessage, pv_arrByte)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginSendRpt(ByRef pv_strMessage As String, ByRef pv_arrByte() As Byte, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements HOSTReportService.IReportWCF.BeginSendRpt
            Return MyBase.Channel.BeginSendRpt(pv_strMessage, pv_arrByte, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndSendRpt(ByRef pv_strMessage As String, ByRef pv_arrByte() As Byte, ByVal result As System.IAsyncResult) As Long Implements HOSTReportService.IReportWCF.EndSendRpt
            Return MyBase.Channel.EndSendRpt(pv_strMessage, pv_arrByte, result)
        End Function
        
        Private Function OnBeginSendRpt(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pv_strMessage As String = CType(inValues(0),String)
            Dim pv_arrByte() As Byte = CType(inValues(1),Byte())
            Return Me.BeginSendRpt(pv_strMessage, pv_arrByte, callback, asyncState)
        End Function
        
        Private Function OnEndSendRpt(ByVal result As System.IAsyncResult) As Object()
            Dim pv_strMessage As String = Me.GetDefaultValueForInitialization(Of String)
            Dim pv_arrByte() As Byte = Me.GetDefaultValueForInitialization(Of Byte())
            Dim retVal As Long = Me.EndSendRpt(pv_strMessage, pv_arrByte, result)
            Return New Object() {pv_strMessage, pv_arrByte, retVal}
        End Function
        
        Private Sub OnSendRptCompleted(ByVal state As Object)
            If (Not (Me.SendRptCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent SendRptCompleted(Me, New SendRptCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub SendRptAsync(ByVal pv_strMessage As String, ByVal pv_arrByte() As Byte)
            Me.SendRptAsync(pv_strMessage, pv_arrByte, Nothing)
        End Sub
        
        Public Overloads Sub SendRptAsync(ByVal pv_strMessage As String, ByVal pv_arrByte() As Byte, ByVal userState As Object)
            If (Me.onBeginSendRptDelegate Is Nothing) Then
                Me.onBeginSendRptDelegate = AddressOf Me.OnBeginSendRpt
            End If
            If (Me.onEndSendRptDelegate Is Nothing) Then
                Me.onEndSendRptDelegate = AddressOf Me.OnEndSendRpt
            End If
            If (Me.onSendRptCompletedDelegate Is Nothing) Then
                Me.onSendRptCompletedDelegate = AddressOf Me.OnSendRptCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSendRptDelegate, New Object() {pv_strMessage, pv_arrByte}, Me.onEndSendRptDelegate, Me.onSendRptCompletedDelegate, userState)
        End Sub
        
        Public Function SendExpRpt(ByVal pv_strMessage As String) As Long Implements HOSTReportService.IReportWCF.SendExpRpt
            Return MyBase.Channel.SendExpRpt(pv_strMessage)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginSendExpRpt(ByVal pv_strMessage As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements HOSTReportService.IReportWCF.BeginSendExpRpt
            Return MyBase.Channel.BeginSendExpRpt(pv_strMessage, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndSendExpRpt(ByVal result As System.IAsyncResult) As Long Implements HOSTReportService.IReportWCF.EndSendExpRpt
            Return MyBase.Channel.EndSendExpRpt(result)
        End Function
        
        Private Function OnBeginSendExpRpt(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pv_strMessage As String = CType(inValues(0),String)
            Return Me.BeginSendExpRpt(pv_strMessage, callback, asyncState)
        End Function
        
        Private Function OnEndSendExpRpt(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Long = Me.EndSendExpRpt(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnSendExpRptCompleted(ByVal state As Object)
            If (Not (Me.SendExpRptCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent SendExpRptCompleted(Me, New SendExpRptCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub SendExpRptAsync(ByVal pv_strMessage As String)
            Me.SendExpRptAsync(pv_strMessage, Nothing)
        End Sub
        
        Public Overloads Sub SendExpRptAsync(ByVal pv_strMessage As String, ByVal userState As Object)
            If (Me.onBeginSendExpRptDelegate Is Nothing) Then
                Me.onBeginSendExpRptDelegate = AddressOf Me.OnBeginSendExpRpt
            End If
            If (Me.onEndSendExpRptDelegate Is Nothing) Then
                Me.onEndSendExpRptDelegate = AddressOf Me.OnEndSendExpRpt
            End If
            If (Me.onSendExpRptCompletedDelegate Is Nothing) Then
                Me.onSendExpRptCompletedDelegate = AddressOf Me.OnSendExpRptCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSendExpRptDelegate, New Object() {pv_strMessage}, Me.onEndSendExpRptDelegate, Me.onSendExpRptCompletedDelegate, userState)
        End Sub
        
        Public Function FetchRpt(ByVal pv_strRptDataKey As String, ByVal pv_intFrom As Integer, ByVal pv_intTo As Integer, ByRef pv_arrByte() As Byte) As Long Implements HOSTReportService.IReportWCF.FetchRpt
            Return MyBase.Channel.FetchRpt(pv_strRptDataKey, pv_intFrom, pv_intTo, pv_arrByte)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginFetchRpt(ByVal pv_strRptDataKey As String, ByVal pv_intFrom As Integer, ByVal pv_intTo As Integer, ByRef pv_arrByte() As Byte, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements HOSTReportService.IReportWCF.BeginFetchRpt
            Return MyBase.Channel.BeginFetchRpt(pv_strRptDataKey, pv_intFrom, pv_intTo, pv_arrByte, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndFetchRpt(ByRef pv_arrByte() As Byte, ByVal result As System.IAsyncResult) As Long Implements HOSTReportService.IReportWCF.EndFetchRpt
            Return MyBase.Channel.EndFetchRpt(pv_arrByte, result)
        End Function
        
        Private Function OnBeginFetchRpt(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pv_strRptDataKey As String = CType(inValues(0),String)
            Dim pv_intFrom As Integer = CType(inValues(1),Integer)
            Dim pv_intTo As Integer = CType(inValues(2),Integer)
            Dim pv_arrByte() As Byte = CType(inValues(3),Byte())
            Return Me.BeginFetchRpt(pv_strRptDataKey, pv_intFrom, pv_intTo, pv_arrByte, callback, asyncState)
        End Function
        
        Private Function OnEndFetchRpt(ByVal result As System.IAsyncResult) As Object()
            Dim pv_arrByte() As Byte = Me.GetDefaultValueForInitialization(Of Byte())
            Dim retVal As Long = Me.EndFetchRpt(pv_arrByte, result)
            Return New Object() {pv_arrByte, retVal}
        End Function
        
        Private Sub OnFetchRptCompleted(ByVal state As Object)
            If (Not (Me.FetchRptCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent FetchRptCompleted(Me, New FetchRptCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub FetchRptAsync(ByVal pv_strRptDataKey As String, ByVal pv_intFrom As Integer, ByVal pv_intTo As Integer, ByVal pv_arrByte() As Byte)
            Me.FetchRptAsync(pv_strRptDataKey, pv_intFrom, pv_intTo, pv_arrByte, Nothing)
        End Sub
        
        Public Overloads Sub FetchRptAsync(ByVal pv_strRptDataKey As String, ByVal pv_intFrom As Integer, ByVal pv_intTo As Integer, ByVal pv_arrByte() As Byte, ByVal userState As Object)
            If (Me.onBeginFetchRptDelegate Is Nothing) Then
                Me.onBeginFetchRptDelegate = AddressOf Me.OnBeginFetchRpt
            End If
            If (Me.onEndFetchRptDelegate Is Nothing) Then
                Me.onEndFetchRptDelegate = AddressOf Me.OnEndFetchRpt
            End If
            If (Me.onFetchRptCompletedDelegate Is Nothing) Then
                Me.onFetchRptCompletedDelegate = AddressOf Me.OnFetchRptCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginFetchRptDelegate, New Object() {pv_strRptDataKey, pv_intFrom, pv_intTo, pv_arrByte}, Me.onEndFetchRptDelegate, Me.onFetchRptCompletedDelegate, userState)
        End Sub
        
        Public Function SendRptCA(ByRef pv_strMessage As String, ByRef pv_arrByte() As Byte, ByRef v_strVSDSignature As String, ByRef v_strCAKey As String, ByRef pv_strDataHash As String) As Long Implements HOSTReportService.IReportWCF.SendRptCA
            Return MyBase.Channel.SendRptCA(pv_strMessage, pv_arrByte, v_strVSDSignature, v_strCAKey, pv_strDataHash)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginSendRptCA(ByRef pv_strMessage As String, ByRef pv_arrByte() As Byte, ByRef v_strVSDSignature As String, ByRef v_strCAKey As String, ByRef pv_strDataHash As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements HOSTReportService.IReportWCF.BeginSendRptCA
            Return MyBase.Channel.BeginSendRptCA(pv_strMessage, pv_arrByte, v_strVSDSignature, v_strCAKey, pv_strDataHash, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndSendRptCA(ByRef pv_strMessage As String, ByRef pv_arrByte() As Byte, ByRef v_strVSDSignature As String, ByRef v_strCAKey As String, ByRef pv_strDataHash As String, ByVal result As System.IAsyncResult) As Long Implements HOSTReportService.IReportWCF.EndSendRptCA
            Return MyBase.Channel.EndSendRptCA(pv_strMessage, pv_arrByte, v_strVSDSignature, v_strCAKey, pv_strDataHash, result)
        End Function
        
        Private Function OnBeginSendRptCA(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pv_strMessage As String = CType(inValues(0),String)
            Dim pv_arrByte() As Byte = CType(inValues(1),Byte())
            Dim v_strVSDSignature As String = CType(inValues(2),String)
            Dim v_strCAKey As String = CType(inValues(3),String)
            Dim pv_strDataHash As String = CType(inValues(4),String)
            Return Me.BeginSendRptCA(pv_strMessage, pv_arrByte, v_strVSDSignature, v_strCAKey, pv_strDataHash, callback, asyncState)
        End Function
        
        Private Function OnEndSendRptCA(ByVal result As System.IAsyncResult) As Object()
            Dim pv_strMessage As String = Me.GetDefaultValueForInitialization(Of String)
            Dim pv_arrByte() As Byte = Me.GetDefaultValueForInitialization(Of Byte())
            Dim v_strVSDSignature As String = Me.GetDefaultValueForInitialization(Of String)
            Dim v_strCAKey As String = Me.GetDefaultValueForInitialization(Of String)
            Dim pv_strDataHash As String = Me.GetDefaultValueForInitialization(Of String)
            Dim retVal As Long = Me.EndSendRptCA(pv_strMessage, pv_arrByte, v_strVSDSignature, v_strCAKey, pv_strDataHash, result)
            Return New Object() {pv_strMessage, pv_arrByte, v_strVSDSignature, v_strCAKey, pv_strDataHash, retVal}
        End Function
        
        Private Sub OnSendRptCACompleted(ByVal state As Object)
            If (Not (Me.SendRptCACompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent SendRptCACompleted(Me, New SendRptCACompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub SendRptCAAsync(ByVal pv_strMessage As String, ByVal pv_arrByte() As Byte, ByVal v_strVSDSignature As String, ByVal v_strCAKey As String, ByVal pv_strDataHash As String)
            Me.SendRptCAAsync(pv_strMessage, pv_arrByte, v_strVSDSignature, v_strCAKey, pv_strDataHash, Nothing)
        End Sub
        
        Public Overloads Sub SendRptCAAsync(ByVal pv_strMessage As String, ByVal pv_arrByte() As Byte, ByVal v_strVSDSignature As String, ByVal v_strCAKey As String, ByVal pv_strDataHash As String, ByVal userState As Object)
            If (Me.onBeginSendRptCADelegate Is Nothing) Then
                Me.onBeginSendRptCADelegate = AddressOf Me.OnBeginSendRptCA
            End If
            If (Me.onEndSendRptCADelegate Is Nothing) Then
                Me.onEndSendRptCADelegate = AddressOf Me.OnEndSendRptCA
            End If
            If (Me.onSendRptCACompletedDelegate Is Nothing) Then
                Me.onSendRptCACompletedDelegate = AddressOf Me.OnSendRptCACompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSendRptCADelegate, New Object() {pv_strMessage, pv_arrByte, v_strVSDSignature, v_strCAKey, pv_strDataHash}, Me.onEndSendRptCADelegate, Me.onSendRptCACompletedDelegate, userState)
        End Sub
        
        Public Function SaveFileRptCA(ByVal pv_arrByte() As Byte, ByVal v_strVSDSignature As String, ByVal v_strClientVSDSignature As String, ByVal v_strTLname As String, ByVal v_strRptId As String, ByRef v_strLocalDir As String, ByRef v_strFileName As String, ByVal v_strStatus As String) As Long Implements HOSTReportService.IReportWCF.SaveFileRptCA
            Return MyBase.Channel.SaveFileRptCA(pv_arrByte, v_strVSDSignature, v_strClientVSDSignature, v_strTLname, v_strRptId, v_strLocalDir, v_strFileName, v_strStatus)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginSaveFileRptCA(ByVal pv_arrByte() As Byte, ByVal v_strVSDSignature As String, ByVal v_strClientVSDSignature As String, ByVal v_strTLname As String, ByVal v_strRptId As String, ByRef v_strLocalDir As String, ByRef v_strFileName As String, ByVal v_strStatus As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements HOSTReportService.IReportWCF.BeginSaveFileRptCA
            Return MyBase.Channel.BeginSaveFileRptCA(pv_arrByte, v_strVSDSignature, v_strClientVSDSignature, v_strTLname, v_strRptId, v_strLocalDir, v_strFileName, v_strStatus, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndSaveFileRptCA(ByRef v_strLocalDir As String, ByRef v_strFileName As String, ByVal result As System.IAsyncResult) As Long Implements HOSTReportService.IReportWCF.EndSaveFileRptCA
            Return MyBase.Channel.EndSaveFileRptCA(v_strLocalDir, v_strFileName, result)
        End Function
        
        Private Function OnBeginSaveFileRptCA(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pv_arrByte() As Byte = CType(inValues(0),Byte())
            Dim v_strVSDSignature As String = CType(inValues(1),String)
            Dim v_strClientVSDSignature As String = CType(inValues(2),String)
            Dim v_strTLname As String = CType(inValues(3),String)
            Dim v_strRptId As String = CType(inValues(4),String)
            Dim v_strLocalDir As String = CType(inValues(5),String)
            Dim v_strFileName As String = CType(inValues(6),String)
            Dim v_strStatus As String = CType(inValues(7),String)
            Return Me.BeginSaveFileRptCA(pv_arrByte, v_strVSDSignature, v_strClientVSDSignature, v_strTLname, v_strRptId, v_strLocalDir, v_strFileName, v_strStatus, callback, asyncState)
        End Function
        
        Private Function OnEndSaveFileRptCA(ByVal result As System.IAsyncResult) As Object()
            Dim v_strLocalDir As String = Me.GetDefaultValueForInitialization(Of String)
            Dim v_strFileName As String = Me.GetDefaultValueForInitialization(Of String)
            Dim retVal As Long = Me.EndSaveFileRptCA(v_strLocalDir, v_strFileName, result)
            Return New Object() {v_strLocalDir, v_strFileName, retVal}
        End Function
        
        Private Sub OnSaveFileRptCACompleted(ByVal state As Object)
            If (Not (Me.SaveFileRptCACompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent SaveFileRptCACompleted(Me, New SaveFileRptCACompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub SaveFileRptCAAsync(ByVal pv_arrByte() As Byte, ByVal v_strVSDSignature As String, ByVal v_strClientVSDSignature As String, ByVal v_strTLname As String, ByVal v_strRptId As String, ByVal v_strLocalDir As String, ByVal v_strFileName As String, ByVal v_strStatus As String)
            Me.SaveFileRptCAAsync(pv_arrByte, v_strVSDSignature, v_strClientVSDSignature, v_strTLname, v_strRptId, v_strLocalDir, v_strFileName, v_strStatus, Nothing)
        End Sub
        
        Public Overloads Sub SaveFileRptCAAsync(ByVal pv_arrByte() As Byte, ByVal v_strVSDSignature As String, ByVal v_strClientVSDSignature As String, ByVal v_strTLname As String, ByVal v_strRptId As String, ByVal v_strLocalDir As String, ByVal v_strFileName As String, ByVal v_strStatus As String, ByVal userState As Object)
            If (Me.onBeginSaveFileRptCADelegate Is Nothing) Then
                Me.onBeginSaveFileRptCADelegate = AddressOf Me.OnBeginSaveFileRptCA
            End If
            If (Me.onEndSaveFileRptCADelegate Is Nothing) Then
                Me.onEndSaveFileRptCADelegate = AddressOf Me.OnEndSaveFileRptCA
            End If
            If (Me.onSaveFileRptCACompletedDelegate Is Nothing) Then
                Me.onSaveFileRptCACompletedDelegate = AddressOf Me.OnSaveFileRptCACompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSaveFileRptCADelegate, New Object() {pv_arrByte, v_strVSDSignature, v_strClientVSDSignature, v_strTLname, v_strRptId, v_strLocalDir, v_strFileName, v_strStatus}, Me.onEndSaveFileRptCADelegate, Me.onSaveFileRptCACompletedDelegate, userState)
        End Sub
        
        Public Sub Disconnect(ByVal pv_oClient As Sats.CommonLibrary.Client) Implements HOSTReportService.IReportWCF.Disconnect
            MyBase.Channel.Disconnect(pv_oClient)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginDisconnect(ByVal pv_oClient As Sats.CommonLibrary.Client, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements HOSTReportService.IReportWCF.BeginDisconnect
            Return MyBase.Channel.BeginDisconnect(pv_oClient, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EndDisconnect(ByVal result As System.IAsyncResult) Implements HOSTReportService.IReportWCF.EndDisconnect
            MyBase.Channel.EndDisconnect(result)
        End Sub
        
        Private Function OnBeginDisconnect(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pv_oClient As Sats.CommonLibrary.Client = CType(inValues(0),Sats.CommonLibrary.Client)
            Return Me.BeginDisconnect(pv_oClient, callback, asyncState)
        End Function
        
        Private Function OnEndDisconnect(ByVal result As System.IAsyncResult) As Object()
            Me.EndDisconnect(result)
            Return Nothing
        End Function
        
        Private Sub OnDisconnectCompleted(ByVal state As Object)
            If (Not (Me.DisconnectCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent DisconnectCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub DisconnectAsync(ByVal pv_oClient As Sats.CommonLibrary.Client)
            Me.DisconnectAsync(pv_oClient, Nothing)
        End Sub
        
        Public Overloads Sub DisconnectAsync(ByVal pv_oClient As Sats.CommonLibrary.Client, ByVal userState As Object)
            If (Me.onBeginDisconnectDelegate Is Nothing) Then
                Me.onBeginDisconnectDelegate = AddressOf Me.OnBeginDisconnect
            End If
            If (Me.onEndDisconnectDelegate Is Nothing) Then
                Me.onEndDisconnectDelegate = AddressOf Me.OnEndDisconnect
            End If
            If (Me.onDisconnectCompletedDelegate Is Nothing) Then
                Me.onDisconnectCompletedDelegate = AddressOf Me.OnDisconnectCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginDisconnectDelegate, New Object() {pv_oClient}, Me.onEndDisconnectDelegate, Me.onDisconnectCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
