'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class AppCore_frmSearch_VN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sats.AppCore.frmSearch_VN", GetType(AppCore_frmSearch_VN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.
        '''</summary>
        Friend Shared ReadOnly Property btnAdd() As String
            Get
                Return ResourceManager.GetString("btnAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ....
        '''</summary>
        Friend Shared ReadOnly Property btnBrown() As String
            Get
                Return ResourceManager.GetString("btnBrown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load DL.
        '''</summary>
        Friend Shared ReadOnly Property btnLoad() As String
            Get
                Return ResourceManager.GetString("btnLoad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.
        '''</summary>
        Friend Shared ReadOnly Property btnNext() As String
            Get
                Return ResourceManager.GetString("btnNext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property btnPre() As String
            Get
                Return ResourceManager.GetString("btnPre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property btnRemove() As String
            Get
                Return ResourceManager.GetString("btnRemove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7.
        '''</summary>
        Friend Shared ReadOnly Property btnRemoveAll() As String
            Get
                Return ResourceManager.GetString("btnRemoveAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Tìm kiếm.
        '''</summary>
        Friend Shared ReadOnly Property btnSearch() As String
            Get
                Return ResourceManager.GetString("btnSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Đây là footer, không thể xem, sửa, xoá dữ liệu!.
        '''</summary>
        Friend Shared ReadOnly Property Footer() As String
            Get
                Return ResourceManager.GetString("Footer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Điều kiện.
        '''</summary>
        Friend Shared ReadOnly Property grbCondition() As String
            Get
                Return ResourceManager.GetString("grbCondition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Danh sách điều kiện tìm kiếm:.
        '''</summary>
        Friend Shared ReadOnly Property grbConditionList() As String
            Get
                Return ResourceManager.GetString("grbConditionList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Điều kiện tìm kiếm:.
        '''</summary>
        Friend Shared ReadOnly Property grbSearchFilter() As String
            Get
                Return ResourceManager.GetString("grbSearchFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết quả tìm kiếm:.
        '''</summary>
        Friend Shared ReadOnly Property grbSearchResult() As String
            Get
                Return ResourceManager.GetString("grbSearchResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tổng số bản ghi tìm kiếm: .
        '''</summary>
        Friend Shared ReadOnly Property GridEx_FooterRow() As String
            Get
                Return ResourceManager.GetString("GridEx_FooterRow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Từ dòng .
        '''</summary>
        Friend Shared ReadOnly Property GridEx_FooterRowFrom() As String
            Get
                Return ResourceManager.GetString("GridEx_FooterRowFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to trong tổng số @ dòng.
        '''</summary>
        Friend Shared ReadOnly Property GridEx_FooterRowIn() As String
            Get
                Return ResourceManager.GetString("GridEx_FooterRowIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to đến dòng .
        '''</summary>
        Friend Shared ReadOnly Property GridEx_FooterRowTo() As String
            Get
                Return ResourceManager.GetString("GridEx_FooterRowTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hãy kéo cột cần nhóm vào đây! (F6: Focus to grid, F7: Prev, F8: Next, F9: Choose).
        '''</summary>
        Friend Shared ReadOnly Property GridEx_GroupByRow() As String
            Get
                Return ResourceManager.GetString("GridEx_GroupByRow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin file.
        '''</summary>
        Friend Shared ReadOnly Property grpFileInfo() As String
            Get
                Return ResourceManager.GetString("grpFileInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tiêu chí:.
        '''</summary>
        Friend Shared ReadOnly Property lbField() As String
            Get
                Return ResourceManager.GetString("lbField", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Đường dẫn file:.
        '''</summary>
        Friend Shared ReadOnly Property lblFilePath() As String
            Get
                Return ResourceManager.GetString("lblFilePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loại file GD:.
        '''</summary>
        Friend Shared ReadOnly Property lblFileType() As String
            Get
                Return ResourceManager.GetString("lblFileType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Số dòng:.
        '''</summary>
        Friend Shared ReadOnly Property lblNum() As String
            Get
                Return ResourceManager.GetString("lblNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Điều kiện:.
        '''</summary>
        Friend Shared ReadOnly Property lbOperator() As String
            Get
                Return ResourceManager.GetString("lbOperator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Giá trị:.
        '''</summary>
        Friend Shared ReadOnly Property lbValue() As String
            Get
                Return ResourceManager.GetString("lbValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tổng số bản ghi: .
        '''</summary>
        Friend Shared ReadOnly Property Searched() As String
            Get
                Return ResourceManager.GetString("Searched", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
