'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmBatch_VN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sats.frmBatch_VN", GetType(frmBatch_VN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Thoát.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Chấp nhận.
        '''</summary>
        Friend Shared ReadOnly Property btnOk() As String
            Get
                Return ResourceManager.GetString("btnOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chưa kết thúc ngày !.
        '''</summary>
        Friend Shared ReadOnly Property ErrorMsg_BEGINOFDAY() As String
            Get
                Return ResourceManager.GetString("ErrorMsg_BEGINOFDAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Đã kết thúc ngày !.
        '''</summary>
        Friend Shared ReadOnly Property ErrorMsg_ENDOFDAY() As String
            Get
                Return ResourceManager.GetString("ErrorMsg_ENDOFDAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Đã có lỗi khi thực hiện, liên hệ với quản trị hệ thống để được giúp đỡ!.
        '''</summary>
        Friend Shared ReadOnly Property Faild() As String
            Get
                Return ResourceManager.GetString("Faild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bắt đầu ngày.
        '''</summary>
        Friend Shared ReadOnly Property frmBatch_BEGINOFDAY() As String
            Get
                Return ResourceManager.GetString("frmBatch_BEGINOFDAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết thúc ngày.
        '''</summary>
        Friend Shared ReadOnly Property frmBatch_ENDOFDAY() As String
            Get
                Return ResourceManager.GetString("frmBatch_ENDOFDAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property grbSA() As String
            Get
                Return ResourceManager.GetString("grbSA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chi nhánh.
        '''</summary>
        Friend Shared ReadOnly Property lbBranchId() As String
            Get
                Return ResourceManager.GetString("lbBranchId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bắt đầu ngày.
        '''</summary>
        Friend Shared ReadOnly Property lbCaption_BEGINOFDAY() As String
            Get
                Return ResourceManager.GetString("lbCaption_BEGINOFDAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết thúc ngày.
        '''</summary>
        Friend Shared ReadOnly Property lbCaption_ENDOFDAY() As String
            Get
                Return ResourceManager.GetString("lbCaption_ENDOFDAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày bắt đầu.
        '''</summary>
        Friend Shared ReadOnly Property lblCurrDate_BEGINOFDAY() As String
            Get
                Return ResourceManager.GetString("lblCurrDate_BEGINOFDAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày kết thúc.
        '''</summary>
        Friend Shared ReadOnly Property lblCurrDate_ENDOFDAY() As String
            Get
                Return ResourceManager.GetString("lblCurrDate_ENDOFDAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Giao dịch thành công!.
        '''</summary>
        Friend Shared ReadOnly Property Success() As String
            Get
                Return ResourceManager.GetString("Success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông báo.
        '''</summary>
        Friend Shared ReadOnly Property Title() As String
            Get
                Return ResourceManager.GetString("Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bạn có muốn bỏ qua các giao dịch chưa xác nhận để kết thúc ngày hay không ?.
        '''</summary>
        Friend Shared ReadOnly Property YesNo() As String
            Get
                Return ResourceManager.GetString("YesNo", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
