'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmRGMI_VN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sats.frmRGMI_VN", GetType(frmRGMI_VN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm mới dữ liệu thành công.
        '''</summary>
        Friend Shared ReadOnly Property AddnewSuccessful() As String
            Get
                Return ResourceManager.GetString("AddnewSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Apply.
        '''</summary>
        Friend Shared ReadOnly Property btnApply() As String
            Get
                Return ResourceManager.GetString("btnApply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Thoát.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Chấp nhận.
        '''</summary>
        Friend Shared ReadOnly Property btnOk() As String
            Get
                Return ResourceManager.GetString("btnOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loại hình.
        '''</summary>
        Friend Shared ReadOnly Property cboType() As String
            Get
                Return ResourceManager.GetString("cboType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cập nhật dữ liệu thành công.
        '''</summary>
        Friend Shared ReadOnly Property EditSuccessful() As String
            Get
                Return ResourceManager.GetString("EditSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã đăng ký TVLK đã tồn tại ! Xin vui lòng nhập lại.
        '''</summary>
        Friend Shared ReadOnly Property ERR_RG_MI_ACCTNO_DUPLICATED() As String
            Get
                Return ResourceManager.GetString("ERR_RG_MI_ACCTNO_DUPLICATED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TVLK này có số ĐKKD và ngày cấp trùng với số ĐKKD và ngày cấp của tổ chức &quot;ISNAME&quot;, bạn có chắc chắn 2 tổ chức này là một không? Chọn Yes để chấp nhận hoặc No để hủy bỏ việc thêm mới TVLK.
        '''</summary>
        Friend Shared ReadOnly Property ERR_RG_MI_BUSSINESSNO_DUPLICATED_IS() As String
            Get
                Return ResourceManager.GetString("ERR_RG_MI_BUSSINESSNO_DUPLICATED_IS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã giao dịch TVLK đã tồn tại ! Xin vui lòng nhập lại..
        '''</summary>
        Friend Shared ReadOnly Property ERR_RG_MI_CODETRADE_DUPLICATED() As String
            Get
                Return ResourceManager.GetString("ERR_RG_MI_CODETRADE_DUPLICATED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Khi TVLK là TCLK bạn phải nhập trường GD qua.
        '''</summary>
        Friend Shared ReadOnly Property FillCbCoMICODE() As String
            Get
                Return ResourceManager.GetString("FillCbCoMICODE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Đăng ký TVLK.
        '''</summary>
        Friend Shared ReadOnly Property frmRGMI() As String
            Get
                Return ResourceManager.GetString("frmRGMI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin.
        '''</summary>
        Friend Shared ReadOnly Property grbInfor() As String
            Get
                Return ResourceManager.GetString("grbInfor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Khởi tạo cửa sổ thất bại.
        '''</summary>
        Friend Shared ReadOnly Property InitDialogFailed() As String
            Get
                Return ResourceManager.GetString("InitDialogFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Số TK.
        '''</summary>
        Friend Shared ReadOnly Property lbAcctNo() As String
            Get
                Return ResourceManager.GetString("lbAcctNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trụ sở chính.
        '''</summary>
        Friend Shared ReadOnly Property lbAddress() As String
            Get
                Return ResourceManager.GetString("lbAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã tự tăng.
        '''</summary>
        Friend Shared ReadOnly Property lbAutoID() As String
            Get
                Return ResourceManager.GetString("lbAutoID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Số tài khoản.
        '''</summary>
        Friend Shared ReadOnly Property lbBankAccount() As String
            Get
                Return ResourceManager.GetString("lbBankAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chi nhánh.
        '''</summary>
        Friend Shared ReadOnly Property lbBankBranch() As String
            Get
                Return ResourceManager.GetString("lbBankBranch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngân hàng.
        '''</summary>
        Friend Shared ReadOnly Property lbBankName() As String
            Get
                Return ResourceManager.GetString("lbBankName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày cấp.
        '''</summary>
        Friend Shared ReadOnly Property lbBusinessDate() As String
            Get
                Return ResourceManager.GetString("lbBusinessDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nơi cấp.
        '''</summary>
        Friend Shared ReadOnly Property lbBusinessIssuer() As String
            Get
                Return ResourceManager.GetString("lbBusinessIssuer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Số ĐKKD.
        '''</summary>
        Friend Shared ReadOnly Property lbBusinessNo() As String
            Get
                Return ResourceManager.GetString("lbBusinessNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vốn ĐL (&apos;000).
        '''</summary>
        Friend Shared ReadOnly Property lbCapital() As String
            Get
                Return ResourceManager.GetString("lbCapital", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vốn PĐ (&apos;000).
        '''</summary>
        Friend Shared ReadOnly Property lbCapitalRule() As String
            Get
                Return ResourceManager.GetString("lbCapitalRule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm mới TVLK.
        '''</summary>
        Friend Shared ReadOnly Property lbCaption() As String
            Get
                Return ResourceManager.GetString("lbCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin quản lý TVLK.
        '''</summary>
        Friend Shared ReadOnly Property lbCaption0() As String
            Get
                Return ResourceManager.GetString("lbCaption0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm mới TVLK.
        '''</summary>
        Friend Shared ReadOnly Property lbCaption1() As String
            Get
                Return ResourceManager.GetString("lbCaption1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sửa thông tin TVLK.
        '''</summary>
        Friend Shared ReadOnly Property lbCaption2() As String
            Get
                Return ResourceManager.GetString("lbCaption2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã GD.
        '''</summary>
        Friend Shared ReadOnly Property lbCode() As String
            Get
                Return ResourceManager.GetString("lbCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fax.
        '''</summary>
        Friend Shared ReadOnly Property lbFax() As String
            Get
                Return ResourceManager.GetString("lbFax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày cấp.
        '''</summary>
        Friend Shared ReadOnly Property lbFirmDate() As String
            Get
                Return ResourceManager.GetString("lbFirmDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nơi cấp.
        '''</summary>
        Friend Shared ReadOnly Property lbFirmIssuer() As String
            Get
                Return ResourceManager.GetString("lbFirmIssuer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Giấy phép CNTVLK.
        '''</summary>
        Friend Shared ReadOnly Property lbFirmNo() As String
            Get
                Return ResourceManager.GetString("lbFirmNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày cấp.
        '''</summary>
        Friend Shared ReadOnly Property lbFoundationDate() As String
            Get
                Return ResourceManager.GetString("lbFoundationDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nơi cấp.
        '''</summary>
        Friend Shared ReadOnly Property lbFoundationIssuer() As String
            Get
                Return ResourceManager.GetString("lbFoundationIssuer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Giấy phép TL.
        '''</summary>
        Friend Shared ReadOnly Property lbFoundationNo() As String
            Get
                Return ResourceManager.GetString("lbFoundationNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GD qua.
        '''</summary>
        Friend Shared ReadOnly Property lbGDBy() As String
            Get
                Return ResourceManager.GetString("lbGDBy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Số ĐK TVLK.
        '''</summary>
        Friend Shared ReadOnly Property lbID() As String
            Get
                Return ResourceManager.GetString("lbID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HĐ Tự doanh.
        '''</summary>
        Friend Shared ReadOnly Property lbIsMember() As String
            Get
                Return ResourceManager.GetString("lbIsMember", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tên TVLK.
        '''</summary>
        Friend Shared ReadOnly Property lbName() As String
            Get
                Return ResourceManager.GetString("lbName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tên GD.
        '''</summary>
        Friend Shared ReadOnly Property lbNameGD() As String
            Get
                Return ResourceManager.GetString("lbNameGD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quốc tịch.
        '''</summary>
        Friend Shared ReadOnly Property lbNationality() As String
            Get
                Return ResourceManager.GetString("lbNationality", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghi chú.
        '''</summary>
        Friend Shared ReadOnly Property lbNotes() As String
            Get
                Return ResourceManager.GetString("lbNotes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày cấp.
        '''</summary>
        Friend Shared ReadOnly Property lbOperationDate() As String
            Get
                Return ResourceManager.GetString("lbOperationDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nơi cấp.
        '''</summary>
        Friend Shared ReadOnly Property lbOperationIssuer() As String
            Get
                Return ResourceManager.GetString("lbOperationIssuer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Giấy phép HĐLK.
        '''</summary>
        Friend Shared ReadOnly Property lbOperationNo() As String
            Get
                Return ResourceManager.GetString("lbOperationNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Điện thoại.
        '''</summary>
        Friend Shared ReadOnly Property lbPhone() As String
            Get
                Return ResourceManager.GetString("lbPhone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Số CMND.
        '''</summary>
        Friend Shared ReadOnly Property lbRepID() As String
            Get
                Return ResourceManager.GetString("lbRepID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Người đại diện.
        '''</summary>
        Friend Shared ReadOnly Property lbRepName() As String
            Get
                Return ResourceManager.GetString("lbRepName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày cấp.
        '''</summary>
        Friend Shared ReadOnly Property lbRetrievalDate() As String
            Get
                Return ResourceManager.GetString("lbRetrievalDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QĐ chấm dứt HĐLK.
        '''</summary>
        Friend Shared ReadOnly Property lbRetrievalNo() As String
            Get
                Return ResourceManager.GetString("lbRetrievalNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trạng thái.
        '''</summary>
        Friend Shared ReadOnly Property lbStatus() As String
            Get
                Return ResourceManager.GetString("lbStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loại TVLK.
        '''</summary>
        Friend Shared ReadOnly Property lbType1() As String
            Get
                Return ResourceManager.GetString("lbType1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loại hình.
        '''</summary>
        Friend Shared ReadOnly Property lbType2() As String
            Get
                Return ResourceManager.GetString("lbType2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trường &quot;@&quot; không được để trống.
        '''</summary>
        Friend Shared ReadOnly Property Mandatory() As String
            Get
                Return ResourceManager.GetString("Mandatory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Số TK đã tồn tại.
        '''</summary>
        Friend Shared ReadOnly Property MICODEExist() As String
            Get
                Return ResourceManager.GetString("MICODEExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã ĐK đã tồn tại.
        '''</summary>
        Friend Shared ReadOnly Property MICodeNumExist() As String
            Get
                Return ResourceManager.GetString("MICodeNumExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã GD đã tồn tại.
        '''</summary>
        Friend Shared ReadOnly Property MICodeTradeExist() As String
            Get
                Return ResourceManager.GetString("MICodeTradeExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TVLK là chi nhánh NHNN nên quốc tịch phải là nước ngoài.
        '''</summary>
        Friend Shared ReadOnly Property MiMustIsForeign() As String
            Get
                Return ResourceManager.GetString("MiMustIsForeign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TVLK không phải là chi nhánh NHNN nên quốc tịch phải là Việt Nam.
        '''</summary>
        Friend Shared ReadOnly Property MiMustIsLocal() As String
            Get
                Return ResourceManager.GetString("MiMustIsLocal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tên TVLK đã tồn tại.
        '''</summary>
        Friend Shared ReadOnly Property MINameExist() As String
            Get
                Return ResourceManager.GetString("MINameExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trường &quot;@&quot; nhập không đúng.
        '''</summary>
        Friend Shared ReadOnly Property NumericDataType() As String
            Get
                Return ResourceManager.GetString("NumericDataType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cập nhật không thành công!.
        '''</summary>
        Friend Shared ReadOnly Property SavingFailed() As String
            Get
                Return ResourceManager.GetString("SavingFailed", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
