'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmTLTXUserAuth_VN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sats.frmTLTXUserAuth_VN", GetType(frmTLTXUserAuth_VN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm mới dữ liệu thành công!.
        '''</summary>
        Friend Shared ReadOnly Property AddnewSuccessful() As String
            Get
                Return ResourceManager.GetString("AddnewSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã nhóm hoặc người sử dụng không tồn tại.  Vui lòng nhập lại!.
        '''</summary>
        Friend Shared ReadOnly Property AuthIdNotExist() As String
            Get
                Return ResourceManager.GetString("AuthIdNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân quyền.
        '''</summary>
        Friend Shared ReadOnly Property brpInfo() As String
            Get
                Return ResourceManager.GetString("brpInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Chấp nhận.
        '''</summary>
        Friend Shared ReadOnly Property btnApply() As String
            Get
                Return ResourceManager.GetString("btnApply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Thoát.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Chấp nhận.
        '''</summary>
        Friend Shared ReadOnly Property btnOK() As String
            Get
                Return ResourceManager.GetString("btnOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cập nhập dữ liệu thành công!.
        '''</summary>
        Friend Shared ReadOnly Property EditSuccessful() As String
            Get
                Return ResourceManager.GetString("EditSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã nhóm hoặc người sử dụng trống. Vui lòng nhập lại !.
        '''</summary>
        Friend Shared ReadOnly Property EmptyAuthId() As String
            Get
                Return ResourceManager.GetString("EmptyAuthId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Đã tồn tại phân cấp mức duyệt của nhóm hoặc người sử dụng cho giao dịch này!.
        '''</summary>
        Friend Shared ReadOnly Property ERR_SA_TLXUSERAUTH_DUPLICATED() As String
            Get
                Return ResourceManager.GetString("ERR_SA_TLXUSERAUTH_DUPLICATED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân mức duyệt giao dịch chi tiết theo nhóm người sử dụng.
        '''</summary>
        Friend Shared ReadOnly Property frmTLTXUserAuth() As String
            Get
                Return ResourceManager.GetString("frmTLTXUserAuth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân cấp giao dịch.
        '''</summary>
        Friend Shared ReadOnly Property grbInfo() As String
            Get
                Return ResourceManager.GetString("grbInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không khởi tạo được cửa sổ!.
        '''</summary>
        Friend Shared ReadOnly Property InitDialogFailed() As String
            Get
                Return ResourceManager.GetString("InitDialogFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã nhóm hoặc người sử dụng.
        '''</summary>
        Friend Shared ReadOnly Property lbAuthId() As String
            Get
                Return ResourceManager.GetString("lbAuthId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tên nhóm hoặc người sử dụng.
        '''</summary>
        Friend Shared ReadOnly Property lbAuthName() As String
            Get
                Return ResourceManager.GetString("lbAuthName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loại phân cấp.
        '''</summary>
        Friend Shared ReadOnly Property lbAuthType() As String
            Get
                Return ResourceManager.GetString("lbAuthType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân mức duyệt giao dịch chi tiết theo nhóm người sử dụng.
        '''</summary>
        Friend Shared ReadOnly Property lbCaption() As String
            Get
                Return ResourceManager.GetString("lbCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân mức duyệt giao dịch chi tiết theo nhóm người sử dụng.
        '''</summary>
        Friend Shared ReadOnly Property lbCaption0() As String
            Get
                Return ResourceManager.GetString("lbCaption0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân mức duyệt giao dịch chi tiết theo nhóm người sử dụng.
        '''</summary>
        Friend Shared ReadOnly Property lbCaption1() As String
            Get
                Return ResourceManager.GetString("lbCaption1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân mức duyệt giao dịch chi tiết theo nhóm người sử dụng.
        '''</summary>
        Friend Shared ReadOnly Property lbCaption2() As String
            Get
                Return ResourceManager.GetString("lbCaption2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duyệt cấp lãnh đạo TTLK.
        '''</summary>
        Friend Shared ReadOnly Property lbCfrId() As String
            Get
                Return ResourceManager.GetString("lbCfrId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duyệt cấp trưởng TVLK.
        '''</summary>
        Friend Shared ReadOnly Property lbChkId() As String
            Get
                Return ResourceManager.GetString("lbChkId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân hệ.
        '''</summary>
        Friend Shared ReadOnly Property lbModCode() As String
            Get
                Return ResourceManager.GetString("lbModCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (F5 để chọn).
        '''</summary>
        Friend Shared ReadOnly Property lbNote() As String
            Get
                Return ResourceManager.GetString("lbNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duyệt cấp chuyên viên TTLK.
        '''</summary>
        Friend Shared ReadOnly Property lbOffId() As String
            Get
                Return ResourceManager.GetString("lbOffId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Giao dịch.
        '''</summary>
        Friend Shared ReadOnly Property lbTltx() As String
            Get
                Return ResourceManager.GetString("lbTltx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân cấp theo nhóm.
        '''</summary>
        Friend Shared ReadOnly Property rbtGroup() As String
            Get
                Return ResourceManager.GetString("rbtGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân cấp theo người dùng.
        '''</summary>
        Friend Shared ReadOnly Property rbtUser() As String
            Get
                Return ResourceManager.GetString("rbtUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không thể thêm mới hoặc sửa thông tin!.
        '''</summary>
        Friend Shared ReadOnly Property SavingFailed() As String
            Get
                Return ResourceManager.GetString("SavingFailed", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
