'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmForeignNoReg_VN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sats.AppCore.frmForeignNoReg_VN", GetType(frmForeignNoReg_VN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Thoát.
        '''</summary>
        Friend Shared ReadOnly Property btnExit() As String
            Get
                Return ResourceManager.GetString("btnExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Sinh mã.
        '''</summary>
        Friend Shared ReadOnly Property btnGenerate() As String
            Get
                Return ResourceManager.GetString("btnGenerate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Chấp nhận.
        '''</summary>
        Friend Shared ReadOnly Property btnOk() As String
            Get
                Return ResourceManager.GetString("btnOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã NĐT nước ngoài này đã tồn tại..
        '''</summary>
        Friend Shared ReadOnly Property ForeignNoDuplicated() As String
            Get
                Return ResourceManager.GetString("ForeignNoDuplicated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bạn chưa sinh mã NĐT nước ngoài.
        '''</summary>
        Friend Shared ReadOnly Property ForeignNoEmpty() As String
            Get
                Return ResourceManager.GetString("ForeignNoEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã NĐT nước ngoài không đúng định đạng cho phép..
        '''</summary>
        Friend Shared ReadOnly Property ForeignNoFormatError() As String
            Get
                Return ResourceManager.GetString("ForeignNoFormatError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cấp mã nhà đầu tư nước ngoài.
        '''</summary>
        Friend Shared ReadOnly Property frmForeignNoReg() As String
            Get
                Return ResourceManager.GetString("frmForeignNoReg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chỉ cấp mã NĐT NN cho các NĐT có loại hình sở hữu là 4 hoặc 6. Vui lòng chọn lại loại hình sở hữu của NĐT.
        '''</summary>
        Friend Shared ReadOnly Property IaTypeNotCorrect() As String
            Get
                Return ResourceManager.GetString("IaTypeNotCorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã NĐT nước ngoài.
        '''</summary>
        Friend Shared ReadOnly Property lbForeignNo() As String
            Get
                Return ResourceManager.GetString("lbForeignNo", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
