'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmAddMFToTLTX_VN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sats.frmAddMFToTLTX_VN", GetType(frmAddMFToTLTX_VN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.
        '''</summary>
        Friend Shared ReadOnly Property btnAdd() As String
            Get
                Return ResourceManager.GetString("btnAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 8.
        '''</summary>
        Friend Shared ReadOnly Property btnAddAll() As String
            Get
                Return ResourceManager.GetString("btnAddAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Thoát.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Xác nhận.
        '''</summary>
        Friend Shared ReadOnly Property btnConfirm() As String
            Get
                Return ResourceManager.GetString("btnConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Chấp nhận.
        '''</summary>
        Friend Shared ReadOnly Property btnOk() As String
            Get
                Return ResourceManager.GetString("btnOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property btnRemove() As String
            Get
                Return ResourceManager.GetString("btnRemove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7.
        '''</summary>
        Friend Shared ReadOnly Property btnRemoveAll() As String
            Get
                Return ResourceManager.GetString("btnRemoveAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không thể bỏ ra NSD hiện thời!.
        '''</summary>
        Friend Shared ReadOnly Property CurrentUser() As String
            Get
                Return ResourceManager.GetString("CurrentUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cập nhật dữ liệu thành công!.
        '''</summary>
        Friend Shared ReadOnly Property EditSuccessful() As String
            Get
                Return ResourceManager.GetString("EditSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bạn phải chọn mức phí trước khi gán giao dịch..
        '''</summary>
        Friend Shared ReadOnly Property EmptyMF() As String
            Get
                Return ResourceManager.GetString("EmptyMF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gán mức tính phí cho giao dịch.
        '''</summary>
        Friend Shared ReadOnly Property frmAddMFToTLTX() As String
            Get
                Return ResourceManager.GetString("frmAddMFToTLTX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin giao dịch.
        '''</summary>
        Friend Shared ReadOnly Property grbMFToTLTXCD() As String
            Get
                Return ResourceManager.GetString("grbMFToTLTXCD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không khởi tạo được cửa sổ!.
        '''</summary>
        Friend Shared ReadOnly Property InitDialogFailed() As String
            Get
                Return ResourceManager.GetString("InitDialogFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gán mức tính phí cho giao dịch.
        '''</summary>
        Friend Shared ReadOnly Property lbCaption() As String
            Get
                Return ResourceManager.GetString("lbCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chọn mức phí.
        '''</summary>
        Friend Shared ReadOnly Property lbMF() As String
            Get
                Return ResourceManager.GetString("lbMF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (F5 để chọn).
        '''</summary>
        Friend Shared ReadOnly Property lbNote() As String
            Get
                Return ResourceManager.GetString("lbNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Danh sách GD đã được gán phí:.
        '''</summary>
        Friend Shared ReadOnly Property lbTLTXCDInMF() As String
            Get
                Return ResourceManager.GetString("lbTLTXCDInMF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Danh sách GD chưa được gán phí:.
        '''</summary>
        Friend Shared ReadOnly Property lbTLTXCDNoMF() As String
            Get
                Return ResourceManager.GetString("lbTLTXCDNoMF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Giao dịch này không tồn tại.
        '''</summary>
        Friend Shared ReadOnly Property MFNotExist() As String
            Get
                Return ResourceManager.GetString("MFNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bạn chưa chọn NSD nào!.
        '''</summary>
        Friend Shared ReadOnly Property NothingSelected() As String
            Get
                Return ResourceManager.GetString("NothingSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Đã có lỗi xẩy ra hãy liên hệ với Quản trị hệ thống!.
        '''</summary>
        Friend Shared ReadOnly Property SavingFailed() As String
            Get
                Return ResourceManager.GetString("SavingFailed", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
