'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmExportData_VN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sats.frmExportData_VN", GetType(frmExportData_VN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết xuất dữ liệu thành công!.
        '''</summary>
        Friend Shared ReadOnly Property AddnewSuccessful() As String
            Get
                Return ResourceManager.GetString("AddnewSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Thoát.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Kết xuất.
        '''</summary>
        Friend Shared ReadOnly Property btnOk() As String
            Get
                Return ResourceManager.GetString("btnOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin Tổ chức phát hành.
        '''</summary>
        Friend Shared ReadOnly Property cbIs() As String
            Get
                Return ResourceManager.GetString("cbIs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin TCPH.
        '''</summary>
        Friend Shared ReadOnly Property cbIs1() As String
            Get
                Return ResourceManager.GetString("cbIs1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin Thành viên lưu ý.
        '''</summary>
        Friend Shared ReadOnly Property cbMi() As String
            Get
                Return ResourceManager.GetString("cbMi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin Ngân hàng.
        '''</summary>
        Friend Shared ReadOnly Property cbMi1() As String
            Get
                Return ResourceManager.GetString("cbMi1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin số liệu Room.
        '''</summary>
        Friend Shared ReadOnly Property cbRoom() As String
            Get
                Return ResourceManager.GetString("cbRoom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin Chứng khoán.
        '''</summary>
        Friend Shared ReadOnly Property cbSi() As String
            Get
                Return ResourceManager.GetString("cbSi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin TP.
        '''</summary>
        Friend Shared ReadOnly Property cbSi1() As String
            Get
                Return ResourceManager.GetString("cbSi1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Giao dịch NHNN.
        '''</summary>
        Friend Shared ReadOnly Property cbTrans() As String
            Get
                Return ResourceManager.GetString("cbTrans", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File &apos;@&apos; đã tồn tại. Bạn có muốn ghi đè lên file cũ không?.
        '''</summary>
        Friend Shared ReadOnly Property FileExist() As String
            Get
                Return ResourceManager.GetString("FileExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết xuất số liệu.
        '''</summary>
        Friend Shared ReadOnly Property frmExportData() As String
            Get
                Return ResourceManager.GetString("frmExportData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin.
        '''</summary>
        Friend Shared ReadOnly Property grbInfoBanks() As String
            Get
                Return ResourceManager.GetString("grbInfoBanks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin.
        '''</summary>
        Friend Shared ReadOnly Property grbInfoStocks() As String
            Get
                Return ResourceManager.GetString("grbInfoStocks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chi nhánh.
        '''</summary>
        Friend Shared ReadOnly Property lbBranch() As String
            Get
                Return ResourceManager.GetString("lbBranch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chi nhánh.
        '''</summary>
        Friend Shared ReadOnly Property lbBranch2() As String
            Get
                Return ResourceManager.GetString("lbBranch2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chi nhánh.
        '''</summary>
        Friend Shared ReadOnly Property lbBranch3() As String
            Get
                Return ResourceManager.GetString("lbBranch3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chi nhánh.
        '''</summary>
        Friend Shared ReadOnly Property lbBranch4() As String
            Get
                Return ResourceManager.GetString("lbBranch4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chi nhánh.
        '''</summary>
        Friend Shared ReadOnly Property lbBranch5() As String
            Get
                Return ResourceManager.GetString("lbBranch5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chi nhánh.
        '''</summary>
        Friend Shared ReadOnly Property lbBranch6() As String
            Get
                Return ResourceManager.GetString("lbBranch6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết xuất số liệu.
        '''</summary>
        Friend Shared ReadOnly Property lbCaption() As String
            Get
                Return ResourceManager.GetString("lbCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lý do lùi thanh toán.
        '''</summary>
        Friend Shared ReadOnly Property lbCsErrType() As String
            Get
                Return ResourceManager.GetString("lbCsErrType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày giao dịch.
        '''</summary>
        Friend Shared ReadOnly Property lbDate() As String
            Get
                Return ResourceManager.GetString("lbDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày giao dịch.
        '''</summary>
        Friend Shared ReadOnly Property lbDate2() As String
            Get
                Return ResourceManager.GetString("lbDate2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày giao dịch.
        '''</summary>
        Friend Shared ReadOnly Property lbDate3() As String
            Get
                Return ResourceManager.GetString("lbDate3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày giao dịch.
        '''</summary>
        Friend Shared ReadOnly Property lbDate4() As String
            Get
                Return ResourceManager.GetString("lbDate4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chu kỳ thanh toán.
        '''</summary>
        Friend Shared ReadOnly Property lbFrequence() As String
            Get
                Return ResourceManager.GetString("lbFrequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thời điểm kết xuất.
        '''</summary>
        Friend Shared ReadOnly Property lbFrequence2() As String
            Get
                Return ResourceManager.GetString("lbFrequence2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Từ.
        '''</summary>
        Friend Shared ReadOnly Property lbFromDate() As String
            Get
                Return ResourceManager.GetString("lbFromDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hình thức thanh toán.
        '''</summary>
        Friend Shared ReadOnly Property lbPayMode() As String
            Get
                Return ResourceManager.GetString("lbPayMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Đến.
        '''</summary>
        Friend Shared ReadOnly Property lbToDate() As String
            Get
                Return ResourceManager.GetString("lbToDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bạn chưa chọn loại thông tin kết xuất!.
        '''</summary>
        Friend Shared ReadOnly Property NotSelectValue() As String
            Get
                Return ResourceManager.GetString("NotSelectValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TT Song phương.
        '''</summary>
        Friend Shared ReadOnly Property rbBiPartite() As String
            Get
                Return ResourceManager.GetString("rbBiPartite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TT Trực tiếp.
        '''</summary>
        Friend Shared ReadOnly Property rbDirect() As String
            Get
                Return ResourceManager.GetString("rbDirect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TT Đa phương.
        '''</summary>
        Friend Shared ReadOnly Property rbMultiPartite() As String
            Get
                Return ResourceManager.GetString("rbMultiPartite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết xuất số liệu cho NHCĐ Thanh toán.
        '''</summary>
        Friend Shared ReadOnly Property tpBanks() As String
            Get
                Return ResourceManager.GetString("tpBanks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết xuất số liệu Thanh toán (lùi TT) NHCĐTT.
        '''</summary>
        Friend Shared ReadOnly Property tpBanks2() As String
            Get
                Return ResourceManager.GetString("tpBanks2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết xuất số liệu Giải tỏa (lùi TT) NHCĐTT.
        '''</summary>
        Friend Shared ReadOnly Property tpBanks3() As String
            Get
                Return ResourceManager.GetString("tpBanks3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết xuất số liệu Chứng quyền.
        '''</summary>
        Friend Shared ReadOnly Property tpCW() As String
            Get
                Return ResourceManager.GetString("tpCW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết xuất số liệu cho Sở giao dịch NHNN.
        '''</summary>
        Friend Shared ReadOnly Property tpNHNN() As String
            Get
                Return ResourceManager.GetString("tpNHNN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết xuất số liệu.
        '''</summary>
        Friend Shared ReadOnly Property tpStocks() As String
            Get
                Return ResourceManager.GetString("tpStocks", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
