'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmExportExcelForm_VN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sats.frmExportExcelForm_VN", GetType(frmExportExcelForm_VN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse....
        '''</summary>
        Friend Shared ReadOnly Property btnBrowse() As String
            Get
                Return ResourceManager.GetString("btnBrowse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Thoát.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Kết xuất.
        '''</summary>
        Friend Shared ReadOnly Property btnOk() As String
            Get
                Return ResourceManager.GetString("btnOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export mẫu file excel cho các giao dịch Import..
        '''</summary>
        Friend Shared ReadOnly Property frmExportExcelForm() As String
            Get
                Return ResourceManager.GetString("frmExportExcelForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin.
        '''</summary>
        Friend Shared ReadOnly Property grbInfo() As String
            Get
                Return ResourceManager.GetString("grbInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export mẫu file excel cho các giao dịch Import..
        '''</summary>
        Friend Shared ReadOnly Property lbCaption() As String
            Get
                Return ResourceManager.GetString("lbCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Địa chỉ mẫu file.
        '''</summary>
        Friend Shared ReadOnly Property lbFileLocation() As String
            Get
                Return ResourceManager.GetString("lbFileLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân hệ.
        '''</summary>
        Friend Shared ReadOnly Property lbSysPart() As String
            Get
                Return ResourceManager.GetString("lbSysPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Giao dịch.
        '''</summary>
        Friend Shared ReadOnly Property lbTransCode() As String
            Get
                Return ResourceManager.GetString("lbTransCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bạn chưa chọn nơi lưu trữ file và tên file.Vui lòng chọn lại..
        '''</summary>
        Friend Shared ReadOnly Property NotInputFileName() As String
            Get
                Return ResourceManager.GetString("NotInputFileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không phải là giao dịch import file nên không thể export mẫu file tương ứng..
        '''</summary>
        Friend Shared ReadOnly Property NotIsImportTransaction() As String
            Get
                Return ResourceManager.GetString("NotIsImportTransaction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân hệ này không có giao dịch Import nào! .
        '''</summary>
        Friend Shared ReadOnly Property NoTransaction() As String
            Get
                Return ResourceManager.GetString("NoTransaction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không có giao dịch nào được chọn để export mẫu file..
        '''</summary>
        Friend Shared ReadOnly Property NotSelectTransaction() As String
            Get
                Return ResourceManager.GetString("NotSelectTransaction", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
