'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmSysVarSetting_VN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sats.frmSysVarSetting_VN", GetType(frmSysVarSetting_VN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.
        '''</summary>
        Friend Shared ReadOnly Property btnAddOne() As String
            Get
                Return ResourceManager.GetString("btnAddOne", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Thoát.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Khởi tạo năm.
        '''</summary>
        Friend Shared ReadOnly Property btnInitAll() As String
            Get
                Return ResourceManager.GetString("btnInitAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Chấp nhận.
        '''</summary>
        Friend Shared ReadOnly Property btnOk() As String
            Get
                Return ResourceManager.GetString("btnOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7.
        '''</summary>
        Friend Shared ReadOnly Property btnRemoveAll() As String
            Get
                Return ResourceManager.GetString("btnRemoveAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property btnRemoveOne() As String
            Get
                Return ResourceManager.GetString("btnRemoveOne", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bạn có chắc chắn muốn thêm ngày này vào danh sách hay không?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmAddOne() As String
            Get
                Return ResourceManager.GetString("ConfirmAddOne", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bạn có chắc chắn muốn xóa toàn bộ ngày nghỉ trong danh sách hay không?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRemoveAll() As String
            Get
                Return ResourceManager.GetString("ConfirmRemoveAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bạn có chắc chắn muốn xóa ngày nghỉ này trong danh sách hay không?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRemoveOne() As String
            Get
                Return ResourceManager.GetString("ConfirmRemoveOne", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày nghỉ này đã tồn tại trong danh sách.
        '''</summary>
        Friend Shared ReadOnly Property DateExist() As String
            Get
                Return ResourceManager.GetString("DateExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cập nhật dữ liệu thành công!.
        '''</summary>
        Friend Shared ReadOnly Property EditSuccessful() As String
            Get
                Return ResourceManager.GetString("EditSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Danh sách ngày nghỉ đang trống.
        '''</summary>
        Friend Shared ReadOnly Property EmptyListBox() As String
            Get
                Return ResourceManager.GetString("EmptyListBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chức năng Thiết lập tham số hệ thống.
        '''</summary>
        Friend Shared ReadOnly Property frmSysVarSetting() As String
            Get
                Return ResourceManager.GetString("frmSysVarSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property grbSA() As String
            Get
                Return ResourceManager.GetString("grbSA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quỹ hỗ trợ thanh toán.
        '''</summary>
        Friend Shared ReadOnly Property grbSF() As String
            Get
                Return ResourceManager.GetString("grbSF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cấu hình.
        '''</summary>
        Friend Shared ReadOnly Property grbSYSTEM() As String
            Get
                Return ResourceManager.GetString("grbSYSTEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nhập năm khởi tạo không chính xác. Vui lòng thực hiện lại việc khởi tạo năm.
        '''</summary>
        Friend Shared ReadOnly Property InitAllError() As String
            Get
                Return ResourceManager.GetString("InitAllError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chỉ cho phép khởi tạo năm từ 2000 đến 2020. Vui lòng thực hiện lại việc khởi tạo năm!.
        '''</summary>
        Friend Shared ReadOnly Property InitAllErrorRange() As String
            Get
                Return ResourceManager.GetString("InitAllErrorRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Khởi tạo năm thành công!.
        '''</summary>
        Friend Shared ReadOnly Property InitAllSuccessfull() As String
            Get
                Return ResourceManager.GetString("InitAllSuccessfull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tỉ lệ đóng góp hàng năm theo giá trị giao dịch MG(%).
        '''</summary>
        Friend Shared ReadOnly Property lbAnnualFundRate() As String
            Get
                Return ResourceManager.GetString("lbAnnualFundRate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chi nhánh.
        '''</summary>
        Friend Shared ReadOnly Property lbBranchId() As String
            Get
                Return ResourceManager.GetString("lbBranchId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thiết lập tham số hệ thống.
        '''</summary>
        Friend Shared ReadOnly Property lbCaption() As String
            Get
                Return ResourceManager.GetString("lbCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chọn ngày nghỉ cho hệ thống:.
        '''</summary>
        Friend Shared ReadOnly Property lbChooseDate() As String
            Get
                Return ResourceManager.GetString("lbChooseDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày giới hạn nếu quá sẽ tính lãi phạt mức 2(ngày).
        '''</summary>
        Friend Shared ReadOnly Property lbDateLimitLevel2() As String
            Get
                Return ResourceManager.GetString("lbDateLimitLevel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mật khẩu kết nối FTP.
        '''</summary>
        Friend Shared ReadOnly Property lbFTPPassword() As String
            Get
                Return ResourceManager.GetString("lbFTPPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Địa chỉ máy chủ FTP.
        '''</summary>
        Friend Shared ReadOnly Property lbFTPServerAddress() As String
            Get
                Return ResourceManager.GetString("lbFTPServerAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cổng kết nối máy chủ FTP.
        '''</summary>
        Friend Shared ReadOnly Property lbFTPServerPort() As String
            Get
                Return ResourceManager.GetString("lbFTPServerPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tên user kết nối FTP.
        '''</summary>
        Friend Shared ReadOnly Property lbFTPUserName() As String
            Get
                Return ResourceManager.GetString("lbFTPUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lãi phạt mức 1 (%/ngày).
        '''</summary>
        Friend Shared ReadOnly Property lbInterestRateLevel1() As String
            Get
                Return ResourceManager.GetString("lbInterestRateLevel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lãi phạt mức 2 (%/ngày).
        '''</summary>
        Friend Shared ReadOnly Property lbInterestRateLevel2() As String
            Get
                Return ResourceManager.GetString("lbInterestRateLevel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Danh sách ngày nghỉ/tháng.
        '''</summary>
        Friend Shared ReadOnly Property lbListDate() As String
            Get
                Return ResourceManager.GetString("lbListDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Số tiền đóng góp tối đa của TVLK hàng năm (triệu).
        '''</summary>
        Friend Shared ReadOnly Property lbMaxAnnualFund() As String
            Get
                Return ResourceManager.GetString("lbMaxAnnualFund", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Số dòng tra cứu tối đa.
        '''</summary>
        Friend Shared ReadOnly Property lbMaxRowSearch() As String
            Get
                Return ResourceManager.GetString("lbMaxRowSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Địa chỉ gốc máy chủ FTP.
        '''</summary>
        Friend Shared ReadOnly Property lbSearchResultPath() As String
            Get
                Return ResourceManager.GetString("lbSearchResultPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân hệ RA.
        '''</summary>
        Friend Shared ReadOnly Property tpRA() As String
            Get
                Return ResourceManager.GetString("tpRA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân hệ SA.
        '''</summary>
        Friend Shared ReadOnly Property tpSA() As String
            Get
                Return ResourceManager.GetString("tpSA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phân hệ SF.
        '''</summary>
        Friend Shared ReadOnly Property tpSF() As String
            Get
                Return ResourceManager.GetString("tpSF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cấu hình hệ thống.
        '''</summary>
        Friend Shared ReadOnly Property tpSYSTEM() As String
            Get
                Return ResourceManager.GetString("tpSYSTEM", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
